# Author : Mark Fioravanti (mfioravanti1994@my.fit.edu)
#          Florida Institute of Technology
# Course : CSE5400 Special Topics - Algebraic Data Structures
# Date   : 10/01/2013
# File   : builder.rb
#
# Summary: The build will take an XML configuration file and use the options
#          to build the procedures for an expert.

require 'rubygems'
require 'nokogiri'

require_relative '../generic/generic'
require_relative '../procedure/procedure'
require_relative '../helpers'
require_relative 'builder/phase'
require_relative 'model'

module Maadi
  module Expert
    module Builder
    class Builder < Maadi::Generic::Generic
      # type (String) is a convenient human readable label.
      def initialize
        super('Builder')

        @tests = Array.new

        @options['BUILD-NAME'] = ''
        @notes['BUILD-NAME'] = 'XML file which contains the build script'
      end

      # prepare will setup the execution environment.  No tests will be executed but all required
      # resources and services will be prepared to execution.
      # return (bool) true if all of the components are read.
      def prepare
        if File.exists?( "../lib/custom/expert/builders/#{@options['BUILD-NAME']}.xml" )
          Maadi::post_message(:More, "Builder (#{@type}) loading files")

          fXML = File.open( "../lib/custom/expert/builders/#{@options['BUILD-NAME']}.xml" )
          doc = Nokogiri::XML(fXML)
          fXML.close

          @test_nodes = doc.xpath('//tests/test')
          @test_nodes.each do |test|
            @tests.push test['name']
          end
          #puts @tests.inspect

        else
          Maadi::post_message(:Warn, "Builder (#{@type}) unable to access files")
          return false
        end

        Maadi::post_message(:More, "Builder (#{@type}) is ready")
        super
      end

      # provide a list of possible tests
      # return (Array of Strings) with each element representing the name of
      # a test that this domain expert can generate
      def tests
        return @tests
      end

      # create a specific test procedure that can be executed against an application.
      # test (String) name of a test (must be on the list generated by the tests function)
      # parameters (Array of Parameters) array of selected parameters for the desired test
      # return (Procedure) return complete test procedure that is ready to be executed.
      def procedure( test, procedure, expert, model )
        if @test_nodes == nil
          return procedure
        end

        phase = @test_nodes.at("test[@name='#{test}']/phases")['default']
        if procedure != nil
          phase = procedure.id
        end
        phase_node = @test_nodes.at("test[@name='#{test}']/phases/phase[@name='#{phase}']")
        if phase_node != nil
          phase = Maadi::Expert::Builder::Phase.new( phase_node, expert, model )
          procedure = phase.process( procedure, expert, model )
        end

        return procedure
      end

      # teardown the object if any database connections, files, etc. are open.
      def teardown
        Maadi::post_message(:Less, "Builder (#{@type}) is NO longer ready")
        super
      end

      def self.is_builder?( builder )
        if builder != nil
          if builder.is_a?( Maadi::Expert::Builder )
            return true
          end
        end

        return false
      end
    end
      end
  end
end